server:
  port: 8080

spring:
  redis:
    database: 0
    timeout: 3000
    password: zhuge
      #    sentinel:    #哨兵模式
      #      master: mymaster #主服务器所在集群名称
    #      nodes: 192.168.0.60:26379,192.168.0.60:26380,192.168.0.60:26381
    cluster:
      nodes: 192.168.0.61:8001,192.168.0.62:8002,192.168.0.63:8003,192.168.0.61:8004,192.168.0.62:8005,192.168.0.63:8006
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000

